export const GET_ALL_DOCTORS = 'Home/GET_ALL_DOCTORS';
export const SET_ALL_DOCTORS = 'Home/SET_ALL_DOCTORS';
export const SET_APPOINTMENTS = 'Home/SET_APPOINTMENTS';
export const GET_APPOINTMENTS = 'Home/GET_APPOINTMENTS';
export const ACCEPT_APPOINTMENT = 'Home/ACCEPT_APPOINTMENT';
export const DENY_APPOINTMENT = 'Home/DENY_APPOINTMENT';
export const CHANGE_STATUS_APPOINTMENT = 'Home/CHANGE_STATUS_APPOINTMENT';
export const REMOVE_APPOINTMENT = 'Home/REMOVE_APPOINTMENT';
