export const SET_APPOINTMENTS = 'UserAppointment/SET_APPOINTMENTS';
export const GET_APPOINTMENTS = 'UserAppointment/GET_APPOINTMENTS';

export const MIDTRANS_PAYMENT = 'MIDTRANS_PAYMENT'
export const SET_MIDTRANS_TOKEN = 'SET_MIDTRANS_TOKEN'

export const EDIT_STATUS_APPOINTMENTS = 'EDIT_STATUS_APPOINTMENTS'