export const CHANGE_PASSWORD_USER = 'CHANGE_PASSWORD_USER';
export const SET_CHANGE_PASSWORD_USER = 'SET_CHANGE_PASSWORD_USER';
export const CHANGE_PASSWORD_DOCTOR = 'CHANGE_PASSWORD_DOCTOR';
export const SET_CHANGE_PASSWORD_DOCTOR = 'SET_CHANGE_PASSWORD_DOCTOR';
export const RESET_CHANGE_PASSWORD = 'REST_CHANGE_PASSWORD'